# Use official nvidia libs for orin

FROM  nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3
# no interation when installing
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# run the setup script
RUN apt update && apt install -y --no-install-recommends\
    python3-pip \
    python3-dev \
    git \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*



COPY requirements.txt .

RUN pip3 install --no-cache-dir --index-url https://pypi.jetson-ai-lab.io/jp6/cu126 torch torchvision \
    pip3 install --no-cache-dir -r requirements.txt

COPY src /app/src


CMD ["python3", "src/main.py"]
