# Use official nvidia libs for orin

# This is arm64 so  cuda wont work for x86 dev devices.
# FROM nvcr.io/nvidia/l4t-jetpack:r36.4.2
FROM nvidia/cuda:12.4.1-devel-ubuntu22.04
# no interation when installing
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# run the setup script
# quick tidbit,  we do this all at once so that the image resizes. if we do multiple runs it splits into 3 layers of action. rm at the end of the layer jsut leaves empty space but no resize

RUN apt update && apt install -y --no-install-recommends python3-pip python3-dev git ffmpeg libsm6 libxext6 \
    libsm6 \
    libxext6 \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


# Install x86 CUDA torchwheels % opencv for testing
RUN pip3 install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cu124 \
                  && pip3 install --no-cache-dir opencv-python onnxruntime-gpu

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt


COPY src /app/src


CMD ["python3", "src/main.py"]
